const items = [
    {
        id: "1",
        title: "Шпагат Macrametr 4 мм, 100 нитей",
        strCategory: "macrame",
        strCategoryTitle: "Макраме",
        price: 332,
        discount: 0,
        colors: [
            { color: "#EEAA56", image: "./img/catalog/items/item01.png" },
            { color: "#81292F", image: "./img/catalog/items/item01-2.png" },
            { color: "#BDBDBD", image: "./img/catalog/items/item01-3.jpg" },
            { color: "#D8C1AA", image: "./img/catalog/items/item01.png" },
            { color: "#EED53A", image: "./img/catalog/items/item01-5.webp" },
            { color: "#FFFFFF", image: "./img/catalog/items/item01-6.webp" }
        ],
        type: "Шпагат, шнуры, веревки",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Macrametr",
        producerCountry: "россия",
        diameter: "4 мм",
        itemLength: "100 м",
        imageUrl: "./img/catalog/items/item01.png",
        feedbacks: [{
            user: "Евгения Доценко",
            dateTime: "13.06.2021 12:30",
            comment: "хороший шпагат.",
            userLogo: "./img/user-foto.jpg",
            rating: 5
        },
        {
            user: "Очумелые ручки",
            dateTime: "15.06.2021 11:42",
            comment: "Качественный, нить прочная. Рекомендую к покупке.",
            userLogo: "./img/user-foto.jpg",
            rating: 5
        },
        {
            user: "Юлия",
            dateTime: "01.07.2021 22:18",
            comment: "все соответствует описанию, но вопросы возникли по доставке.",
            userLogo: "./img/user-foto.jpg",
            rating: 4
        }
        ],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."

    },
    {
        id: "2",
        title: "Шпагат джутовый Сибшнур 500 м",
        strCategory: "macrame",
        strCategoryTitle: "Макраме",
        price: 422,
        discount: 385,
        colors: [
            { color: "#9D856B", image: "./img/catalog/items/item02.png" },
            { color: "#B69882", image: "./img/catalog/items/item01-2.png" },
            { color: "#CFBBAC", image: "./img/catalog/items/item01-3.jpg" }
        ],
        type: "Шпагат, шнуры, веревки",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Сибшнур",
        producerCountry: "Украина",
        diameter: "3 мм",
        itemLength: "100 м",
        imageUrl: "./img/catalog/items/item02.png",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "3",
        title: "Пряжа Arachna \"Macrame MAXI\"",
        strCategory: "macrame",
        strCategoryTitle: "Макраме",
        price: 1092,
        discount: 0,
        colors: [
            { color: "#FAF9F6", image: "./img/catalog/items/item03.png" },
            { color: "#EBD5BC", image: "./img/catalog/items/item01-2.png" },
            { color: "#0395AF", image: "./img/catalog/items/item01-3.jpg" },
            { color: "#F09482", image: "./img/catalog/items/item01-2.png" },
            { color: "#424242", image: "./img/catalog/items/item01-3.jpg" }
        ],
        type: "Пряжа",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Macrametr",
        producerCountry: "россия",
        diameter: "3 мм",
        itemLength: "100 м",
        imageUrl: "./img/catalog/items/item03.png",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "4",
        title: "Пряжа Arachna \"Macrame MINI\"",
        strCategory: "macrame",
        strCategoryTitle: "Макраме",
        price: 1053,
        discount: 0,
        colors: [
            { color: "#FAF9F6", image: "./img/catalog/items/item04.png" },
            { color: "#EBD5BC", image: "./img/catalog/items/item04.png" },
            { color: "#0395AF", image: "./img/catalog/items/item04.png" },
            { color: "#F09482", image: "./img/catalog/items/item04.png" },
            { color: "#424242", image: "./img/catalog/items/item04.png" }
        ],
        type: "Пряжа",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Macrametr",
        producerCountry: "россия",
        diameter: "4 мм",
        itemLength: "100 м",
        imageUrl: "./img/catalog/items/item04.png",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "5",
        title: "Шнур \"Gamma\" 0.8 мм, 50 м",
        strCategory: "macrame",
        strCategoryTitle: "Макраме",
        price: 1053,
        discount: 0,
        colors: [
            { color: "#E5D8CB", image: "./img/catalog/items/item05.png" },
            { color: "#C51212", image: "./img/catalog/items/item05.png" },
            { color: "#FC9257", image: "./img/catalog/items/item05.png" },
            { color: "#1C1C1C", image: "./img/catalog/items/item05.png" },
            { color: "#424242", image: "./img/catalog/items/item05.png" }
        ],
        type: "Шпагат, шнуры, веревки",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Гамма",
        producerCountry: "россия",
        diameter: "0.8 мм",
        itemLength: "100 м",
        imageUrl: "./img/catalog/items/item05.png",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "6",
        title: "Веревка “Zефирка” 4 мм, 100 м",
        strCategory: "macrame",
        strCategoryTitle: "Макраме",
        price: 617,
        discount: 0,
        colors: [
            { color: "#FCF7F4", image: "./img/catalog/items/item06.png" },
            { color: "#FAF0E2", image: "./img/catalog/items/item06.png" },
            { color: "#F24135", image: "./img/catalog/items/item06.png" },
            { color: "#0395AF", image: "./img/catalog/items/item06.png" },
            { color: "#424242", image: "./img/catalog/items/item06.png" }
        ],
        type: "Шпагат, шнуры, веревки",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Зефирка",
        producerCountry: "россия",
        diameter: "4 мм",
        itemLength: "100 м",
        imageUrl: "./img/catalog/items/item06.png",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "7",
        title: "Веревка “Zефирка” 6 мм, 100 м",
        strCategory: "macrame",
        strCategoryTitle: "Макраме",
        price: 617,
        discount: 0,
        colors: [
            { color: "#FCF7F4", image: "./img/catalog/items/item06.png" },
            { color: "#FAF0E2", image: "./img/catalog/items/item06.png" },
            { color: "#F24135", image: "./img/catalog/items/item06.png" },
            { color: "#0395AF", image: "./img/catalog/items/item06.png" },
            { color: "#424242", image: "./img/catalog/items/item06.png" }
        ],
        type: "Шпагат, шнуры, веревки",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Зефирка",
        producerCountry: "россия",
        diameter: "4 мм",
        itemLength: "100 м",
        imageUrl: "./img/catalog/items/item06.png",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "8",
        title: "Трикотажная пряжа Zефирка",
        strCategory: "knitting",
        strCategoryTitle: "Вязание",
        price: 360,
        discount: 0,
        colors: [
            { color: "#696837", image: "./img/catalog/items/item08.png" },
            { color: "#81292F", image: "./img/catalog/items/item08.png" },
            { color: "#D8C1AA", image: "./img/catalog/items/item08.png" },
            { color: "#EED53A", image: "./img/catalog/items/item08.png" },
            { color: "#424242", image: "./img/catalog/items/item08.png" }
        ],
        type: "Пряжа",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Зефирка",
        producerCountry: "россия",
        diameter: "4 мм",
        imageUrl: "./img/catalog/items/item08.png",
        weight: "380 г",
        itemLength: "100 м",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "9",
        title: "Пряжа трикотажная Arachna «Слинг Принт»",
        strCategory: "knitting",
        strCategoryTitle: "Вязание",
        price: 170,
        discount: 135,
        colors: [
            { color: "#696837", image: "./img/catalog/items/item09.png" },
            { color: "#81292F", image: "./img/catalog/items/item09.png" },
            { color: "#D8C1AA", image: "./img/catalog/items/item09.png" },
            { color: "#EED53A", image: "./img/catalog/items/item09.png" },
            { color: "#424242", image: "./img/catalog/items/item09.png" }
        ],
        imageUrl: "./img/catalog/items/item09.png",
        type: "Пряжа",
        composition: [{ name: "Хлопок", quantity: 100 }],
        producer: "Гамма",
        producerCountry: "россия",
        diameter: "4 мм",
        weight: "160 г",
        itemLength: "50 м",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    },
    {
        id: "10",
        title: "Пряжа Katia Merino Flame",
        strCategory: "knitting",
        strCategoryTitle: "Вязание",
        price: 510,
        discount: 0,
        colors: [
            { color: "#FAF9F6", image: "./img/catalog/items/item10.png" },
            { color: "#EBD5BC", image: "./img/catalog/items/item10.png" },
            { color: "#0395AF", image: "./img/catalog/items/item10.png" },
            { color: "#F09482", image: "./img/catalog/items/item10.png" },
            { color: "#2C66A5", image: "./img/catalog/items/item10.png" },
            { color: "#1FA866", image: "./img/catalog/items/item10.png" },
            { color: "#FFB565", image: "./img/catalog/items/item10.png" },
            { color: "#FF65C1", image: "./img/catalog/items/item10.png" },
            { color: "#696837", image: "./img/catalog/items/item10.png" },
            { color: "#FFFFFF", image: "./img/catalog/items/item10.png" },
            { color: "#BDBDBD", image: "./img/catalog/items/item10.png" },
            { color: "#81292F", image: "./img/catalog/items/item10.png" },
            { color: "#D8C1AA", image: "./img/catalog/items/item10.png" },
            { color: "#EED53A", image: "./img/catalog/items/item10.png" },
            { color: "#424242", image: "./img/catalog/items/item10.png" }
        ],
        imageUrl: "./img/catalog/items/item10.png",
        type: "Пряжа",
        producer: "Macrametr",
        producerCountry: "россия",
        diameter: "4 мм",
        composition: [{ name: "Меринос", quantity: 74 }, { name: "Хлопок", quantity: 26 }],
        weight: "50 г",
        itemLength: "80 м",
        feedbacks: [],
        description: "Хлопковый шпагат для рукоделия 4 мм состоит из 100 тонких скрученных нитей. Для создания модных перьев (листьев), кисточек, панно, ловцов снов, брелков, украшений, салфеток, кашпо, наволочек и других изделий в технике макраме. Мягкий и приятный на ощупь, при желании, можно легко расплести в бахрому."
    }
]

export default items;
